/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import NewUser from '../model/NewUser';
import Response from '../model/Response';

/**
 * Admin service.
 * @module api/AdminApi
 * @version 1.2.1
 */
export default class AdminApi {

    /**
     * Constructs a new AdminApi. 
     * @alias module:api/AdminApi
     * @class
     * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
     * default to {@link module:ApiClient#instance} if unspecified.
     */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * BCorrespondent apicreate new user
     * @param {module:model/NewUser} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Response} and HTTP response
     */
    adminUserPutWithHttpInfo(body) {
        let postBody = body;
        // verify the required parameter 'body' is set
        if (body === undefined || body === null) {
            throw new Error("Missing the required parameter 'body' when calling adminUserPut");
        }

        let pathParams = {};
        let queryParams = {};
        let headerParams = {};
        let formParams = {};

        let authNames = ['JwtSecurity'];
        let contentTypes = ['application/json;charset=utf-8'];
        let accepts = ['application/json;charset=utf-8'];
        let returnType = Response;
        return this.apiClient.callApi(
            '/admin/user', 'PUT',
            pathParams, queryParams, headerParams, formParams, postBody,
            authNames, contentTypes, accepts, returnType, null
        );
    }

    /**
     * BCorrespondent apicreate new user
     * @param {module:model/NewUser} body 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Response}
     */
    adminUserPut(body) {
        return this.adminUserPutWithHttpInfo(body)
            .then(function(response_and_data) {
                return response_and_data.data;
            });
    }


}