/**
 * BCorrespondent. Tag (v1.0.0). Commit (9e7bfa7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', process.cwd() + '/src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require(process.cwd() + '/src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.BCorrespondentTagV100Commit9e7bfa7);
    }
}(this, function(expect, BCorrespondentTagV100Commit9e7bfa7) {
    'use strict';

    var instance;

    beforeEach(function() {
        instance = new BCorrespondentTagV100Commit9e7bfa7.FrontendApi();
    });

    var getProperty = function(object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function')
            return object[getter]();
        else
            return object[property];
    }

    var setProperty = function(object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function')
            object[setter](value);
        else
            object[property] = value;
    }

    describe('FrontendApi', function() {
        describe('frontendInitGet', function() {
            it('should call frontendInitGet successfully', function(done) {
                //uncomment below and update the code to test frontendInitGet
                //instance.frontendInitGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('frontendUserDashboardDailyBalanceSheetGapGet', function() {
            it('should call frontendUserDashboardDailyBalanceSheetGapGet successfully', function(done) {
                //uncomment below and update the code to test frontendUserDashboardDailyBalanceSheetGapGet
                //instance.frontendUserDashboardDailyBalanceSheetGapGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('frontendUserDashboardDailyBalanceSheetInitGet', function() {
            it('should call frontendUserDashboardDailyBalanceSheetInitGet successfully', function(done) {
                //uncomment below and update the code to test frontendUserDashboardDailyBalanceSheetInitGet
                //instance.frontendUserDashboardDailyBalanceSheetInitGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('frontendUserDashboardDailyBalanceSheetTimelineDirectionGet', function() {
            it('should call frontendUserDashboardDailyBalanceSheetTimelineDirectionGet successfully', function(done) {
                //uncomment below and update the code to test frontendUserDashboardDailyBalanceSheetTimelineDirectionGet
                //instance.frontendUserDashboardDailyBalanceSheetTimelineDirectionGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('frontendUserDashboardTimelineTransactionIdentGet', function() {
            it('should call frontendUserDashboardTimelineTransactionIdentGet successfully', function(done) {
                //uncomment below and update the code to test frontendUserDashboardTimelineTransactionIdentGet
                //instance.frontendUserDashboardTimelineTransactionIdentGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('frontendUserHistoryGet', function() {
            it('should call frontendUserHistoryGet successfully', function(done) {
                //uncomment below and update the code to test frontendUserHistoryGet
                //instance.frontendUserHistoryGet(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
        describe('frontendUserProcuratoryPut', function() {
            it('should call frontendUserProcuratoryPut successfully', function(done) {
                //uncomment below and update the code to test frontendUserProcuratoryPut
                //instance.frontendUserProcuratoryPut(function(error) {
                //  if (error) throw error;
                //expect().to.be();
                //});
                done();
            });
        });
    });

}));