/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AmountInDayOfWeek from './model/AmountInDayOfWeek';
import AuthCode from './model/AuthCode';
import Balance from './model/Balance';
import BalancedBook from './model/BalancedBook';
import BalancedBookInstitution from './model/BalancedBookInstitution';
import BalancedBookWallet from './model/BalancedBookWallet';
import Credentials from './model/Credentials';
import Currency from './model/Currency';
import DailyBalanceSheet from './model/DailyBalanceSheet';
import DayOfWeeksHourly from './model/DayOfWeeksHourly';
import DayOfWeeksHourlyTotalSum from './model/DayOfWeeksHourlyTotalSum';
import Error from './model/Error';
import Fee from './model/Fee';
import FetchGap from './model/FetchGap';
import GapItem from './model/GapItem';
import GapItemAmount from './model/GapItemAmount';
import GapItemTime from './model/GapItemTime';
import GapItemUnit from './model/GapItemUnit';
import GapItemUnitStatus from './model/GapItemUnitStatus';
import GapItemWrapper from './model/GapItemWrapper';
import HistoryTimeline from './model/HistoryTimeline';
import Init from './model/Init';
import InitDashboard from './model/InitDashboard';
import InitWithdrawal from './model/InitWithdrawal';
import InvoiceRegisterRequest from './model/InvoiceRegisterRequest';
import InvoiceRegisterResponse from './model/InvoiceRegisterResponse';
import InvoiceSince from './model/InvoiceSince';
import Issue from './model/Issue';
import JWTStatus from './model/JWTStatus';
import LogLevel from './model/LogLevel';
import NewPassword from './model/NewPassword';
import NewUser from './model/NewUser';
import Notification from './model/Notification';
import Notifications from './model/Notifications';
import ProcuratoryRequest from './model/ProcuratoryRequest';
import ResendCode from './model/ResendCode';
import Response from './model/Response';
import ResponseAuthCodeHash from './model/ResponseAuthCodeHash';
import ResponseAuthToken from './model/ResponseAuthToken';
import ResponseBalancedBook from './model/ResponseBalancedBook';
import ResponseBool from './model/ResponseBool';
import ResponseFetchGap from './model/ResponseFetchGap';
import ResponseGapItemWrapper from './model/ResponseGapItemWrapper';
import ResponseHistoryTimeline from './model/ResponseHistoryTimeline';
import ResponseIdFile from './model/ResponseIdFile';
import ResponseInit from './model/ResponseInit';
import ResponseInitDashboard from './model/ResponseInitDashboard';
import ResponseInitWithdrawal from './model/ResponseInitWithdrawal';
import ResponseInvoiceRegisterResponse from './model/ResponseInvoiceRegisterResponse';
import ResponseMaybeInt64 from './model/ResponseMaybeInt64';
import ResponseMaybeWithdrawalHistory from './model/ResponseMaybeWithdrawalHistory';
import ResponseNotifications from './model/ResponseNotifications';
import ResponseTimelineTransactionResponse from './model/ResponseTimelineTransactionResponse';
import ResponseWithdrawResult from './model/ResponseWithdrawResult';
import ResponseWorkspace from './model/ResponseWorkspace';
import SendGridSendMailRequest from './model/SendGridSendMailRequest';
import Sha from './model/Sha';
import TimelineTransaction from './model/TimelineTransaction';
import TimelineTransactionResponse from './model/TimelineTransactionResponse';
import Wallet from './model/Wallet';
import WalletType from './model/WalletType';
import WithFieldCodeError from './model/WithFieldCodeError';
import Withdraw from './model/Withdraw';
import WithdrawResult from './model/WithdrawResult';
import WithdrawResultStatus from './model/WithdrawResultStatus';
import WithdrawalHistory from './model/WithdrawalHistory';
import WithdrawalHistoryItem from './model/WithdrawalHistoryItem';
import WithdrawalStatus from './model/WithdrawalStatus';
import Workspace from './model/Workspace';
import AdminApi from './api/AdminApi';
import AuthApi from './api/AuthApi';
import FileApi from './api/FileApi';
import ForeignApi from './api/ForeignApi';
import FrontendApi from './api/FrontendApi';
import InstitutionApi from './api/InstitutionApi';


/**
 * BCorrespondent server api.<br>
 * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
 * <p>
 * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
 * <pre>
 * var BCorrespondentTagCommitBb65df7 = require('index'); // See note below*.
 * var xxxSvc = new BCorrespondentTagCommitBb65df7.XxxApi(); // Allocate the API class we're going to use.
 * var yyyModel = new BCorrespondentTagCommitBb65df7.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
 * and put the application logic within the callback function.</em>
 * </p>
 * <p>
 * A non-AMD browser application (discouraged) might do something like this:
 * <pre>
 * var xxxSvc = new BCorrespondentTagCommitBb65df7.XxxApi(); // Allocate the API class we're going to use.
 * var yyy = new BCorrespondentTagCommitBb65df7.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * </p>
 * @module index
 * @version 1.2.1
 */
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AmountInDayOfWeek model constructor.
     * @property {module:model/AmountInDayOfWeek}
     */
    AmountInDayOfWeek,

    /**
     * The AuthCode model constructor.
     * @property {module:model/AuthCode}
     */
    AuthCode,

    /**
     * The Balance model constructor.
     * @property {module:model/Balance}
     */
    Balance,

    /**
     * The BalancedBook model constructor.
     * @property {module:model/BalancedBook}
     */
    BalancedBook,

    /**
     * The BalancedBookInstitution model constructor.
     * @property {module:model/BalancedBookInstitution}
     */
    BalancedBookInstitution,

    /**
     * The BalancedBookWallet model constructor.
     * @property {module:model/BalancedBookWallet}
     */
    BalancedBookWallet,

    /**
     * The Credentials model constructor.
     * @property {module:model/Credentials}
     */
    Credentials,

    /**
     * The Currency model constructor.
     * @property {module:model/Currency}
     */
    Currency,

    /**
     * The DailyBalanceSheet model constructor.
     * @property {module:model/DailyBalanceSheet}
     */
    DailyBalanceSheet,

    /**
     * The DayOfWeeksHourly model constructor.
     * @property {module:model/DayOfWeeksHourly}
     */
    DayOfWeeksHourly,

    /**
     * The DayOfWeeksHourlyTotalSum model constructor.
     * @property {module:model/DayOfWeeksHourlyTotalSum}
     */
    DayOfWeeksHourlyTotalSum,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Fee model constructor.
     * @property {module:model/Fee}
     */
    Fee,

    /**
     * The FetchGap model constructor.
     * @property {module:model/FetchGap}
     */
    FetchGap,

    /**
     * The GapItem model constructor.
     * @property {module:model/GapItem}
     */
    GapItem,

    /**
     * The GapItemAmount model constructor.
     * @property {module:model/GapItemAmount}
     */
    GapItemAmount,

    /**
     * The GapItemTime model constructor.
     * @property {module:model/GapItemTime}
     */
    GapItemTime,

    /**
     * The GapItemUnit model constructor.
     * @property {module:model/GapItemUnit}
     */
    GapItemUnit,

    /**
     * The GapItemUnitStatus model constructor.
     * @property {module:model/GapItemUnitStatus}
     */
    GapItemUnitStatus,

    /**
     * The GapItemWrapper model constructor.
     * @property {module:model/GapItemWrapper}
     */
    GapItemWrapper,

    /**
     * The HistoryTimeline model constructor.
     * @property {module:model/HistoryTimeline}
     */
    HistoryTimeline,

    /**
     * The Init model constructor.
     * @property {module:model/Init}
     */
    Init,

    /**
     * The InitDashboard model constructor.
     * @property {module:model/InitDashboard}
     */
    InitDashboard,

    /**
     * The InitWithdrawal model constructor.
     * @property {module:model/InitWithdrawal}
     */
    InitWithdrawal,

    /**
     * The InvoiceRegisterRequest model constructor.
     * @property {module:model/InvoiceRegisterRequest}
     */
    InvoiceRegisterRequest,

    /**
     * The InvoiceRegisterResponse model constructor.
     * @property {module:model/InvoiceRegisterResponse}
     */
    InvoiceRegisterResponse,

    /**
     * The InvoiceSince model constructor.
     * @property {module:model/InvoiceSince}
     */
    InvoiceSince,

    /**
     * The Issue model constructor.
     * @property {module:model/Issue}
     */
    Issue,

    /**
     * The JWTStatus model constructor.
     * @property {module:model/JWTStatus}
     */
    JWTStatus,

    /**
     * The LogLevel model constructor.
     * @property {module:model/LogLevel}
     */
    LogLevel,

    /**
     * The NewPassword model constructor.
     * @property {module:model/NewPassword}
     */
    NewPassword,

    /**
     * The NewUser model constructor.
     * @property {module:model/NewUser}
     */
    NewUser,

    /**
     * The Notification model constructor.
     * @property {module:model/Notification}
     */
    Notification,

    /**
     * The Notifications model constructor.
     * @property {module:model/Notifications}
     */
    Notifications,

    /**
     * The ProcuratoryRequest model constructor.
     * @property {module:model/ProcuratoryRequest}
     */
    ProcuratoryRequest,

    /**
     * The ResendCode model constructor.
     * @property {module:model/ResendCode}
     */
    ResendCode,

    /**
     * The Response model constructor.
     * @property {module:model/Response}
     */
    Response,

    /**
     * The ResponseAuthCodeHash model constructor.
     * @property {module:model/ResponseAuthCodeHash}
     */
    ResponseAuthCodeHash,

    /**
     * The ResponseAuthToken model constructor.
     * @property {module:model/ResponseAuthToken}
     */
    ResponseAuthToken,

    /**
     * The ResponseBalancedBook model constructor.
     * @property {module:model/ResponseBalancedBook}
     */
    ResponseBalancedBook,

    /**
     * The ResponseBool model constructor.
     * @property {module:model/ResponseBool}
     */
    ResponseBool,

    /**
     * The ResponseFetchGap model constructor.
     * @property {module:model/ResponseFetchGap}
     */
    ResponseFetchGap,

    /**
     * The ResponseGapItemWrapper model constructor.
     * @property {module:model/ResponseGapItemWrapper}
     */
    ResponseGapItemWrapper,

    /**
     * The ResponseHistoryTimeline model constructor.
     * @property {module:model/ResponseHistoryTimeline}
     */
    ResponseHistoryTimeline,

    /**
     * The ResponseIdFile model constructor.
     * @property {module:model/ResponseIdFile}
     */
    ResponseIdFile,

    /**
     * The ResponseInit model constructor.
     * @property {module:model/ResponseInit}
     */
    ResponseInit,

    /**
     * The ResponseInitDashboard model constructor.
     * @property {module:model/ResponseInitDashboard}
     */
    ResponseInitDashboard,

    /**
     * The ResponseInitWithdrawal model constructor.
     * @property {module:model/ResponseInitWithdrawal}
     */
    ResponseInitWithdrawal,

    /**
     * The ResponseInvoiceRegisterResponse model constructor.
     * @property {module:model/ResponseInvoiceRegisterResponse}
     */
    ResponseInvoiceRegisterResponse,

    /**
     * The ResponseMaybeInt64 model constructor.
     * @property {module:model/ResponseMaybeInt64}
     */
    ResponseMaybeInt64,

    /**
     * The ResponseMaybeWithdrawalHistory model constructor.
     * @property {module:model/ResponseMaybeWithdrawalHistory}
     */
    ResponseMaybeWithdrawalHistory,

    /**
     * The ResponseNotifications model constructor.
     * @property {module:model/ResponseNotifications}
     */
    ResponseNotifications,

    /**
     * The ResponseTimelineTransactionResponse model constructor.
     * @property {module:model/ResponseTimelineTransactionResponse}
     */
    ResponseTimelineTransactionResponse,

    /**
     * The ResponseWithdrawResult model constructor.
     * @property {module:model/ResponseWithdrawResult}
     */
    ResponseWithdrawResult,

    /**
     * The ResponseWorkspace model constructor.
     * @property {module:model/ResponseWorkspace}
     */
    ResponseWorkspace,

    /**
     * The SendGridSendMailRequest model constructor.
     * @property {module:model/SendGridSendMailRequest}
     */
    SendGridSendMailRequest,

    /**
     * The Sha model constructor.
     * @property {module:model/Sha}
     */
    Sha,

    /**
     * The TimelineTransaction model constructor.
     * @property {module:model/TimelineTransaction}
     */
    TimelineTransaction,

    /**
     * The TimelineTransactionResponse model constructor.
     * @property {module:model/TimelineTransactionResponse}
     */
    TimelineTransactionResponse,

    /**
     * The Wallet model constructor.
     * @property {module:model/Wallet}
     */
    Wallet,

    /**
     * The WalletType model constructor.
     * @property {module:model/WalletType}
     */
    WalletType,

    /**
     * The WithFieldCodeError model constructor.
     * @property {module:model/WithFieldCodeError}
     */
    WithFieldCodeError,

    /**
     * The Withdraw model constructor.
     * @property {module:model/Withdraw}
     */
    Withdraw,

    /**
     * The WithdrawResult model constructor.
     * @property {module:model/WithdrawResult}
     */
    WithdrawResult,

    /**
     * The WithdrawResultStatus model constructor.
     * @property {module:model/WithdrawResultStatus}
     */
    WithdrawResultStatus,

    /**
     * The WithdrawalHistory model constructor.
     * @property {module:model/WithdrawalHistory}
     */
    WithdrawalHistory,

    /**
     * The WithdrawalHistoryItem model constructor.
     * @property {module:model/WithdrawalHistoryItem}
     */
    WithdrawalHistoryItem,

    /**
     * The WithdrawalStatus model constructor.
     * @property {module:model/WithdrawalStatus}
     */
    WithdrawalStatus,

    /**
     * The Workspace model constructor.
     * @property {module:model/Workspace}
     */
    Workspace,

    /**
     * The AdminApi service constructor.
     * @property {module:api/AdminApi}
     */
    AdminApi,

    /**
     * The AuthApi service constructor.
     * @property {module:api/AuthApi}
     */
    AuthApi,

    /**
     * The FileApi service constructor.
     * @property {module:api/FileApi}
     */
    FileApi,

    /**
     * The ForeignApi service constructor.
     * @property {module:api/ForeignApi}
     */
    ForeignApi,

    /**
     * The FrontendApi service constructor.
     * @property {module:api/FrontendApi}
     */
    FrontendApi,

    /**
     * The InstitutionApi service constructor.
     * @property {module:api/InstitutionApi}
     */
    InstitutionApi
};