/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AmountInDayOfWeek model module.
 * @module model/AmountInDayOfWeek
 * @version 1.2.1
 */
class AmountInDayOfWeek {
    /**
     * Constructs a new <code>AmountInDayOfWeek</code>.
     * @alias module:model/AmountInDayOfWeek
     * @param total {Number} 
     * @param value {Number} 
     */
    constructor(total, value) {

        AmountInDayOfWeek.initialize(this, total, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, total, value) {
        obj['total'] = total;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>AmountInDayOfWeek</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AmountInDayOfWeek} obj Optional instance to populate.
     * @return {module:model/AmountInDayOfWeek} The populated <code>AmountInDayOfWeek</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AmountInDayOfWeek();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AmountInDayOfWeek</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AmountInDayOfWeek</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AmountInDayOfWeek.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }

    /**
     * minimum: -9223372036854775808
     * maximum: 9223372036854775807
     * @return {Number}
     */
    getTotal() {
        return this.total;
    }

    /**
     * @param {Number} total
     */
    setTotal(total) {
        this['total'] = total;
    }
    /**
     * minimum: -9223372036854775808
     * maximum: 9223372036854775807
     * @return {Number}
     */
    getValue() {
        return this.value;
    }

    /**
     * @param {Number} value
     */
    setValue(value) {
        this['value'] = value;
    }

}

AmountInDayOfWeek.RequiredProperties = ["total", "value"];

/**
 * @member {Number} total
 */
AmountInDayOfWeek.prototype['total'] = undefined;

/**
 * @member {Number} value
 */
AmountInDayOfWeek.prototype['value'] = undefined;






export default AmountInDayOfWeek;