/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthCode model module.
 * @module model/AuthCode
 * @version 1.2.1
 */
class AuthCode {
    /**
     * Constructs a new <code>AuthCode</code>.
     * @alias module:model/AuthCode
     * @param code {Number} 
     * @param hash {String} 
     */
    constructor(code, hash) {

        AuthCode.initialize(this, code, hash);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, hash) {
        obj['code'] = code;
        obj['hash'] = hash;
    }

    /**
     * Constructs a <code>AuthCode</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthCode} obj Optional instance to populate.
     * @return {module:model/AuthCode} The populated <code>AuthCode</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthCode();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthCode</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthCode</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AuthCode.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['hash'] && !(typeof data['hash'] === 'string' || data['hash'] instanceof String)) {
            throw new Error("Expected the field `hash` to be a primitive type in the JSON string but got " + data['hash']);
        }

        return true;
    }

    /**
     * minimum: -9223372036854775808
     * maximum: 9223372036854775807
     * @return {Number}
     */
    getCode() {
        return this.code;
    }

    /**
     * @param {Number} code
     */
    setCode(code) {
        this['code'] = code;
    }
    /**
     * @return {String}
     */
    getHash() {
        return this.hash;
    }

    /**
     * @param {String} hash
     */
    setHash(hash) {
        this['hash'] = hash;
    }

}

AuthCode.RequiredProperties = ["code", "hash"];

/**
 * @member {Number} code
 */
AuthCode.prototype['code'] = undefined;

/**
 * @member {String} hash
 */
AuthCode.prototype['hash'] = undefined;






export default AuthCode;