/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BalancedBookWallet from './BalancedBookWallet';
import DayOfWeeksHourly from './DayOfWeeksHourly';

/**
 * The BalancedBookInstitution model module.
 * @module model/BalancedBookInstitution
 * @version 1.2.1
 */
class BalancedBookInstitution {
    /**
     * Constructs a new <code>BalancedBookInstitution</code>.
     * @alias module:model/BalancedBookInstitution
     * @param balances {Array.<module:model/BalancedBookWallet>} 
     * @param dayOfWeeksHourly {Array.<module:model/DayOfWeeksHourly>} 
     * @param ident {Number} 
     * @param title {String} 
     */
    constructor(balances, dayOfWeeksHourly, ident, title) {

        BalancedBookInstitution.initialize(this, balances, dayOfWeeksHourly, ident, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, balances, dayOfWeeksHourly, ident, title) {
        obj['balances'] = balances;
        obj['dayOfWeeksHourly'] = dayOfWeeksHourly;
        obj['ident'] = ident;
        obj['title'] = title;
    }

    /**
     * Constructs a <code>BalancedBookInstitution</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BalancedBookInstitution} obj Optional instance to populate.
     * @return {module:model/BalancedBookInstitution} The populated <code>BalancedBookInstitution</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BalancedBookInstitution();

            if (data.hasOwnProperty('balances')) {
                obj['balances'] = ApiClient.convertToType(data['balances'], [BalancedBookWallet]);
            }
            if (data.hasOwnProperty('dayOfWeeksHourly')) {
                obj['dayOfWeeksHourly'] = ApiClient.convertToType(data['dayOfWeeksHourly'], [DayOfWeeksHourly]);
            }
            if (data.hasOwnProperty('ident')) {
                obj['ident'] = ApiClient.convertToType(data['ident'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BalancedBookInstitution</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BalancedBookInstitution</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BalancedBookInstitution.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['balances']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['balances'])) {
                throw new Error("Expected the field `balances` to be an array in the JSON data but got " + data['balances']);
            }
            // validate the optional field `balances` (array)
            for (const item of data['balances']) {
                BalancedBookWallet.validateJSON(item);
            };
        }
        if (data['dayOfWeeksHourly']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['dayOfWeeksHourly'])) {
                throw new Error("Expected the field `dayOfWeeksHourly` to be an array in the JSON data but got " + data['dayOfWeeksHourly']);
            }
            // validate the optional field `dayOfWeeksHourly` (array)
            for (const item of data['dayOfWeeksHourly']) {
                DayOfWeeksHourly.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }

        return true;
    }

    /**
     * @return {Array.<module:model/BalancedBookWallet>}
     */
    getBalances() {
        return this.balances;
    }

    /**
     * @param {Array.<module:model/BalancedBookWallet>} balances
     */
    setBalances(balances) {
        this['balances'] = balances;
    }
    /**
     * @return {Array.<module:model/DayOfWeeksHourly>}
     */
    getDayOfWeeksHourly() {
        return this.dayOfWeeksHourly;
    }

    /**
     * @param {Array.<module:model/DayOfWeeksHourly>} dayOfWeeksHourly
     */
    setDayOfWeeksHourly(dayOfWeeksHourly) {
        this['dayOfWeeksHourly'] = dayOfWeeksHourly;
    }
    /**
     * minimum: -9223372036854775808
     * maximum: 9223372036854775807
     * @return {Number}
     */
    getIdent() {
        return this.ident;
    }

    /**
     * @param {Number} ident
     */
    setIdent(ident) {
        this['ident'] = ident;
    }
    /**
     * @return {String}
     */
    getTitle() {
        return this.title;
    }

    /**
     * @param {String} title
     */
    setTitle(title) {
        this['title'] = title;
    }

}

BalancedBookInstitution.RequiredProperties = ["balances", "dayOfWeeksHourly", "ident", "title"];

/**
 * @member {Array.<module:model/BalancedBookWallet>} balances
 */
BalancedBookInstitution.prototype['balances'] = undefined;

/**
 * @member {Array.<module:model/DayOfWeeksHourly>} dayOfWeeksHourly
 */
BalancedBookInstitution.prototype['dayOfWeeksHourly'] = undefined;

/**
 * @member {Number} ident
 */
BalancedBookInstitution.prototype['ident'] = undefined;

/**
 * @member {String} title
 */
BalancedBookInstitution.prototype['title'] = undefined;






export default BalancedBookInstitution;