/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Credentials model module.
 * @module model/Credentials
 * @version 1.2.1
 */
class Credentials {
    /**
     * Constructs a new <code>Credentials</code>.
     * @alias module:model/Credentials
     */
    constructor() {

        Credentials.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) {}

    /**
     * Constructs a <code>Credentials</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Credentials} obj Optional instance to populate.
     * @return {module:model/Credentials} The populated <code>Credentials</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Credentials();

            if (data.hasOwnProperty('browserFp')) {
                obj['browserFp'] = ApiClient.convertToType(data['browserFp'], 'String');
            }
            if (data.hasOwnProperty('login')) {
                obj['login'] = ApiClient.convertToType(data['login'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Credentials</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Credentials</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['browserFp'] && !(typeof data['browserFp'] === 'string' || data['browserFp'] instanceof String)) {
            throw new Error("Expected the field `browserFp` to be a primitive type in the JSON string but got " + data['browserFp']);
        }
        // ensure the json data is a string
        if (data['login'] && !(typeof data['login'] === 'string' || data['login'] instanceof String)) {
            throw new Error("Expected the field `login` to be a primitive type in the JSON string but got " + data['login']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }

        return true;
    }

    /**
     * @return {String}
     */
    getBrowserFp() {
        return this.browserFp;
    }

    /**
     * @param {String} browserFp
     */
    setBrowserFp(browserFp) {
        this['browserFp'] = browserFp;
    }
    /**
     * @return {String}
     */
    getLogin() {
        return this.login;
    }

    /**
     * @param {String} login
     */
    setLogin(login) {
        this['login'] = login;
    }
    /**
     * @return {String}
     */
    getPassword() {
        return this.password;
    }

    /**
     * @param {String} password
     */
    setPassword(password) {
        this['password'] = password;
    }

}



/**
 * @member {String} browserFp
 */
Credentials.prototype['browserFp'] = undefined;

/**
 * @member {String} login
 */
Credentials.prototype['login'] = undefined;

/**
 * @member {String} password
 */
Credentials.prototype['password'] = undefined;






export default Credentials;