/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
 * Enum class Currency.
 * @enum {}
 * @readonly
 */
export default class Currency {

    /**
     * value: "usd"
     * @const
     */
    "usd" = "usd";


    /**
     * value: "eur"
     * @const
     */
    "eur" = "eur";



    /**
     * Returns a <code>Currency</code> enum value from a Javascript object name.
     * @param {Object} data The plain JavaScript object containing the name of the enum value.
     * @return {module:model/Currency} The enum <code>Currency</code> value.
     */
    static constructFromObject(object) {
        return object;
    }
}