/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GapItem from './GapItem';

/**
 * The DailyBalanceSheet model module.
 * @module model/DailyBalanceSheet
 * @version 1.2.1
 */
class DailyBalanceSheet {
    /**
     * Constructs a new <code>DailyBalanceSheet</code>.
     * @alias module:model/DailyBalanceSheet
     * @param gaps {Array.<module:model/GapItem>} 
     * @param institution {String} 
     */
    constructor(gaps, institution) {

        DailyBalanceSheet.initialize(this, gaps, institution);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, gaps, institution) {
        obj['gaps'] = gaps;
        obj['institution'] = institution;
    }

    /**
     * Constructs a <code>DailyBalanceSheet</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DailyBalanceSheet} obj Optional instance to populate.
     * @return {module:model/DailyBalanceSheet} The populated <code>DailyBalanceSheet</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DailyBalanceSheet();

            if (data.hasOwnProperty('gaps')) {
                obj['gaps'] = ApiClient.convertToType(data['gaps'], [GapItem]);
            }
            if (data.hasOwnProperty('institution')) {
                obj['institution'] = ApiClient.convertToType(data['institution'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DailyBalanceSheet</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DailyBalanceSheet</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DailyBalanceSheet.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['gaps']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['gaps'])) {
                throw new Error("Expected the field `gaps` to be an array in the JSON data but got " + data['gaps']);
            }
            // validate the optional field `gaps` (array)
            for (const item of data['gaps']) {
                GapItem.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['institution'] && !(typeof data['institution'] === 'string' || data['institution'] instanceof String)) {
            throw new Error("Expected the field `institution` to be a primitive type in the JSON string but got " + data['institution']);
        }

        return true;
    }

    /**
     * @return {Array.<module:model/GapItem>}
     */
    getGaps() {
        return this.gaps;
    }

    /**
     * @param {Array.<module:model/GapItem>} gaps
     */
    setGaps(gaps) {
        this['gaps'] = gaps;
    }
    /**
     * @return {String}
     */
    getInstitution() {
        return this.institution;
    }

    /**
     * @param {String} institution
     */
    setInstitution(institution) {
        this['institution'] = institution;
    }

}

DailyBalanceSheet.RequiredProperties = ["gaps", "institution"];

/**
 * @member {Array.<module:model/GapItem>} gaps
 */
DailyBalanceSheet.prototype['gaps'] = undefined;

/**
 * @member {String} institution
 */
DailyBalanceSheet.prototype['institution'] = undefined;






export default DailyBalanceSheet;