/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GapItem from './GapItem';

/**
 * The GapItemWrapper model module.
 * @module model/GapItemWrapper
 * @version 1.2.1
 */
class GapItemWrapper {
    /**
     * Constructs a new <code>GapItemWrapper</code>.
     * @alias module:model/GapItemWrapper
     * @param items {Array.<module:model/GapItem>} 
     */
    constructor(items) {

        GapItemWrapper.initialize(this, items);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, items) {
        obj['items'] = items;
    }

    /**
     * Constructs a <code>GapItemWrapper</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GapItemWrapper} obj Optional instance to populate.
     * @return {module:model/GapItemWrapper} The populated <code>GapItemWrapper</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GapItemWrapper();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [GapItem]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GapItemWrapper</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GapItemWrapper</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GapItemWrapper.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                GapItem.validateJSON(item);
            };
        }

        return true;
    }

    /**
     * @return {Array.<module:model/GapItem>}
     */
    getItems() {
        return this.items;
    }

    /**
     * @param {Array.<module:model/GapItem>} items
     */
    setItems(items) {
        this['items'] = items;
    }

}

GapItemWrapper.RequiredProperties = ["items"];

/**
 * @member {Array.<module:model/GapItem>} items
 */
GapItemWrapper.prototype['items'] = undefined;






export default GapItemWrapper;