/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InvoiceSince from './InvoiceSince';
import JWTStatus from './JWTStatus';
import LogLevel from './LogLevel';
import Sha from './Sha';

/**
 * The Init model module.
 * @module model/Init
 * @version 1.2.1
 */
class Init {
    /**
     * Constructs a new <code>Init</code>.
     * @alias module:model/Init
     * @param invoicesince {module:model/InvoiceSince} 
     * @param isjwtvalid {module:model/JWTStatus} 
     * @param level {module:model/LogLevel} 
     * @param loadcsslocally {Boolean} 
     * @param shaxs {Array.<module:model/Sha>} 
     * @param telegrambot {String} 
     * @param telegramchat {String} 
     * @param totelegram {Boolean} 
     */
    constructor(invoicesince, isjwtvalid, level, loadcsslocally, shaxs, telegrambot, telegramchat, totelegram) {

        Init.initialize(this, invoicesince, isjwtvalid, level, loadcsslocally, shaxs, telegrambot, telegramchat, totelegram);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, invoicesince, isjwtvalid, level, loadcsslocally, shaxs, telegrambot, telegramchat, totelegram) {
        obj['invoicesince'] = invoicesince;
        obj['isjwtvalid'] = isjwtvalid;
        obj['level'] = level;
        obj['loadcsslocally'] = loadcsslocally;
        obj['shaxs'] = shaxs;
        obj['telegrambot'] = telegrambot;
        obj['telegramchat'] = telegramchat;
        obj['totelegram'] = totelegram;
    }

    /**
     * Constructs a <code>Init</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Init} obj Optional instance to populate.
     * @return {module:model/Init} The populated <code>Init</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Init();

            if (data.hasOwnProperty('invoicesince')) {
                obj['invoicesince'] = InvoiceSince.constructFromObject(data['invoicesince']);
            }
            if (data.hasOwnProperty('isjwtvalid')) {
                obj['isjwtvalid'] = JWTStatus.constructFromObject(data['isjwtvalid']);
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = LogLevel.constructFromObject(data['level']);
            }
            if (data.hasOwnProperty('loadcsslocally')) {
                obj['loadcsslocally'] = ApiClient.convertToType(data['loadcsslocally'], 'Boolean');
            }
            if (data.hasOwnProperty('shaxs')) {
                obj['shaxs'] = ApiClient.convertToType(data['shaxs'], [Sha]);
            }
            if (data.hasOwnProperty('telegrambot')) {
                obj['telegrambot'] = ApiClient.convertToType(data['telegrambot'], 'String');
            }
            if (data.hasOwnProperty('telegramchat')) {
                obj['telegramchat'] = ApiClient.convertToType(data['telegramchat'], 'String');
            }
            if (data.hasOwnProperty('totelegram')) {
                obj['totelegram'] = ApiClient.convertToType(data['totelegram'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Init</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Init</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Init.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `invoicesince`
        if (data['invoicesince']) { // data not null
            InvoiceSince.validateJSON(data['invoicesince']);
        }
        if (data['shaxs']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['shaxs'])) {
                throw new Error("Expected the field `shaxs` to be an array in the JSON data but got " + data['shaxs']);
            }
            // validate the optional field `shaxs` (array)
            for (const item of data['shaxs']) {
                Sha.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['telegrambot'] && !(typeof data['telegrambot'] === 'string' || data['telegrambot'] instanceof String)) {
            throw new Error("Expected the field `telegrambot` to be a primitive type in the JSON string but got " + data['telegrambot']);
        }
        // ensure the json data is a string
        if (data['telegramchat'] && !(typeof data['telegramchat'] === 'string' || data['telegramchat'] instanceof String)) {
            throw new Error("Expected the field `telegramchat` to be a primitive type in the JSON string but got " + data['telegramchat']);
        }

        return true;
    }

    /**
     * @return {module:model/InvoiceSince}
     */
    getInvoicesince() {
        return this.invoicesince;
    }

    /**
     * @param {module:model/InvoiceSince} invoicesince
     */
    setInvoicesince(invoicesince) {
        this['invoicesince'] = invoicesince;
    }
    /**
     * @return {module:model/JWTStatus}
     */
    getIsjwtvalid() {
        return this.isjwtvalid;
    }

    /**
     * @param {module:model/JWTStatus} isjwtvalid
     */
    setIsjwtvalid(isjwtvalid) {
        this['isjwtvalid'] = isjwtvalid;
    }
    /**
     * @return {module:model/LogLevel}
     */
    getLevel() {
        return this.level;
    }

    /**
     * @param {module:model/LogLevel} level
     */
    setLevel(level) {
        this['level'] = level;
    }
    /**
     * @return {Boolean}
     */
    getLoadcsslocally() {
        return this.loadcsslocally;
    }

    /**
     * @param {Boolean} loadcsslocally
     */
    setLoadcsslocally(loadcsslocally) {
        this['loadcsslocally'] = loadcsslocally;
    }
    /**
     * @return {Array.<module:model/Sha>}
     */
    getShaxs() {
        return this.shaxs;
    }

    /**
     * @param {Array.<module:model/Sha>} shaxs
     */
    setShaxs(shaxs) {
        this['shaxs'] = shaxs;
    }
    /**
     * @return {String}
     */
    getTelegrambot() {
        return this.telegrambot;
    }

    /**
     * @param {String} telegrambot
     */
    setTelegrambot(telegrambot) {
        this['telegrambot'] = telegrambot;
    }
    /**
     * @return {String}
     */
    getTelegramchat() {
        return this.telegramchat;
    }

    /**
     * @param {String} telegramchat
     */
    setTelegramchat(telegramchat) {
        this['telegramchat'] = telegramchat;
    }
    /**
     * @return {Boolean}
     */
    getTotelegram() {
        return this.totelegram;
    }

    /**
     * @param {Boolean} totelegram
     */
    setTotelegram(totelegram) {
        this['totelegram'] = totelegram;
    }

}

Init.RequiredProperties = ["invoicesince", "isjwtvalid", "level", "loadcsslocally", "shaxs", "telegrambot", "telegramchat", "totelegram"];

/**
 * @member {module:model/InvoiceSince} invoicesince
 */
Init.prototype['invoicesince'] = undefined;

/**
 * @member {module:model/JWTStatus} isjwtvalid
 */
Init.prototype['isjwtvalid'] = undefined;

/**
 * @member {module:model/LogLevel} level
 */
Init.prototype['level'] = undefined;

/**
 * @member {Boolean} loadcsslocally
 */
Init.prototype['loadcsslocally'] = undefined;

/**
 * @member {Array.<module:model/Sha>} shaxs
 */
Init.prototype['shaxs'] = undefined;

/**
 * @member {String} telegrambot
 */
Init.prototype['telegrambot'] = undefined;

/**
 * @member {String} telegramchat
 */
Init.prototype['telegramchat'] = undefined;

/**
 * @member {Boolean} totelegram
 */
Init.prototype['totelegram'] = undefined;






export default Init;