/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DailyBalanceSheet from './DailyBalanceSheet';
import Wallet from './Wallet';

/**
 * The InitDashboard model module.
 * @module model/InitDashboard
 * @version 1.2.1
 */
class InitDashboard {
    /**
     * Constructs a new <code>InitDashboard</code>.
     * @alias module:model/InitDashboard
     * @param dailyBalanceSheet {module:model/DailyBalanceSheet} 
     * @param wallets {Array.<module:model/Wallet>} 
     */
    constructor(dailyBalanceSheet, wallets) {

        InitDashboard.initialize(this, dailyBalanceSheet, wallets);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, dailyBalanceSheet, wallets) {
        obj['dailyBalanceSheet'] = dailyBalanceSheet;
        obj['wallets'] = wallets;
    }

    /**
     * Constructs a <code>InitDashboard</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InitDashboard} obj Optional instance to populate.
     * @return {module:model/InitDashboard} The populated <code>InitDashboard</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InitDashboard();

            if (data.hasOwnProperty('dailyBalanceSheet')) {
                obj['dailyBalanceSheet'] = DailyBalanceSheet.constructFromObject(data['dailyBalanceSheet']);
            }
            if (data.hasOwnProperty('wallets')) {
                obj['wallets'] = ApiClient.convertToType(data['wallets'], [Wallet]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InitDashboard</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InitDashboard</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InitDashboard.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `dailyBalanceSheet`
        if (data['dailyBalanceSheet']) { // data not null
            DailyBalanceSheet.validateJSON(data['dailyBalanceSheet']);
        }
        if (data['wallets']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['wallets'])) {
                throw new Error("Expected the field `wallets` to be an array in the JSON data but got " + data['wallets']);
            }
            // validate the optional field `wallets` (array)
            for (const item of data['wallets']) {
                Wallet.validateJSON(item);
            };
        }

        return true;
    }

    /**
     * @return {module:model/DailyBalanceSheet}
     */
    getDailyBalanceSheet() {
        return this.dailyBalanceSheet;
    }

    /**
     * @param {module:model/DailyBalanceSheet} dailyBalanceSheet
     */
    setDailyBalanceSheet(dailyBalanceSheet) {
        this['dailyBalanceSheet'] = dailyBalanceSheet;
    }
    /**
     * @return {Array.<module:model/Wallet>}
     */
    getWallets() {
        return this.wallets;
    }

    /**
     * @param {Array.<module:model/Wallet>} wallets
     */
    setWallets(wallets) {
        this['wallets'] = wallets;
    }

}

InitDashboard.RequiredProperties = ["dailyBalanceSheet", "wallets"];

/**
 * @member {module:model/DailyBalanceSheet} dailyBalanceSheet
 */
InitDashboard.prototype['dailyBalanceSheet'] = undefined;

/**
 * @member {Array.<module:model/Wallet>} wallets
 */
InitDashboard.prototype['wallets'] = undefined;






export default InitDashboard;