/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InvoiceRegisterResponse model module.
 * @module model/InvoiceRegisterResponse
 * @version 1.2.1
 */
class InvoiceRegisterResponse {
    /**
     * Constructs a new <code>InvoiceRegisterResponse</code>.
     * @alias module:model/InvoiceRegisterResponse
     * @param externalIdent {String} 
     */
    constructor(externalIdent) {

        InvoiceRegisterResponse.initialize(this, externalIdent);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, externalIdent) {
        obj['externalIdent'] = externalIdent;
    }

    /**
     * Constructs a <code>InvoiceRegisterResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InvoiceRegisterResponse} obj Optional instance to populate.
     * @return {module:model/InvoiceRegisterResponse} The populated <code>InvoiceRegisterResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvoiceRegisterResponse();

            if (data.hasOwnProperty('externalIdent')) {
                obj['externalIdent'] = ApiClient.convertToType(data['externalIdent'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InvoiceRegisterResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InvoiceRegisterResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InvoiceRegisterResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['externalIdent'] && !(typeof data['externalIdent'] === 'string' || data['externalIdent'] instanceof String)) {
            throw new Error("Expected the field `externalIdent` to be a primitive type in the JSON string but got " + data['externalIdent']);
        }

        return true;
    }

    /**
     * @return {String}
     */
    getExternalIdent() {
        return this.externalIdent;
    }

    /**
     * @param {String} externalIdent
     */
    setExternalIdent(externalIdent) {
        this['externalIdent'] = externalIdent;
    }

}

InvoiceRegisterResponse.RequiredProperties = ["externalIdent"];

/**
 * @member {String} externalIdent
 */
InvoiceRegisterResponse.prototype['externalIdent'] = undefined;






export default InvoiceRegisterResponse;