/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProcuratoryRequest model module.
 * @module model/ProcuratoryRequest
 * @version 1.2.1
 */
class ProcuratoryRequest {
    /**
     * Constructs a new <code>ProcuratoryRequest</code>.
     * @alias module:model/ProcuratoryRequest
     * @param procuratoryTest {String} 
     */
    constructor(procuratoryTest) {

        ProcuratoryRequest.initialize(this, procuratoryTest);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, procuratoryTest) {
        obj['procuratoryTest'] = procuratoryTest;
    }

    /**
     * Constructs a <code>ProcuratoryRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProcuratoryRequest} obj Optional instance to populate.
     * @return {module:model/ProcuratoryRequest} The populated <code>ProcuratoryRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProcuratoryRequest();

            if (data.hasOwnProperty('procuratoryTest')) {
                obj['procuratoryTest'] = ApiClient.convertToType(data['procuratoryTest'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProcuratoryRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProcuratoryRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProcuratoryRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['procuratoryTest'] && !(typeof data['procuratoryTest'] === 'string' || data['procuratoryTest'] instanceof String)) {
            throw new Error("Expected the field `procuratoryTest` to be a primitive type in the JSON string but got " + data['procuratoryTest']);
        }

        return true;
    }

    /**
     * @return {String}
     */
    getProcuratoryTest() {
        return this.procuratoryTest;
    }

    /**
     * @param {String} procuratoryTest
     */
    setProcuratoryTest(procuratoryTest) {
        this['procuratoryTest'] = procuratoryTest;
    }

}

ProcuratoryRequest.RequiredProperties = ["procuratoryTest"];

/**
 * @member {String} procuratoryTest
 */
ProcuratoryRequest.prototype['procuratoryTest'] = undefined;






export default ProcuratoryRequest;