/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Error from './Error';
import WithFieldCodeError from './WithFieldCodeError';

/**
 * The Response model module.
 * @module model/Response
 * @version 1.2.1
 */
class Response {
    /**
     * Constructs a new <code>Response</code>.
     * @alias module:model/Response
     */
    constructor() {

        Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) {}

    /**
     * Constructs a <code>Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Response} obj Optional instance to populate.
     * @return {module:model/Response} The populated <code>Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Response();

            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [WithFieldCodeError]);
            }
            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], [Object]);
            }
            if (data.hasOwnProperty('warnings')) {
                obj['warnings'] = ApiClient.convertToType(data['warnings'], [Error]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Response</code>.
     */
    static validateJSON(data) {
        if (data['errors']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['errors'])) {
                throw new Error("Expected the field `errors` to be an array in the JSON data but got " + data['errors']);
            }
            // validate the optional field `errors` (array)
            for (const item of data['errors']) {
                WithFieldCodeError.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['success'])) {
            throw new Error("Expected the field `success` to be an array in the JSON data but got " + data['success']);
        }
        if (data['warnings']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['warnings'])) {
                throw new Error("Expected the field `warnings` to be an array in the JSON data but got " + data['warnings']);
            }
            // validate the optional field `warnings` (array)
            for (const item of data['warnings']) {
                Error.validateJSON(item);
            };
        }

        return true;
    }

    /**
     * @return {Array.<module:model/WithFieldCodeError>}
     */
    getErrors() {
        return this.errors;
    }

    /**
     * @param {Array.<module:model/WithFieldCodeError>} errors
     */
    setErrors(errors) {
        this['errors'] = errors;
    }
    /**
     * @return {Array.<Object>}
     */
    getSuccess() {
        return this.success;
    }

    /**
     * @param {Array.<Object>} success
     */
    setSuccess(success) {
        this['success'] = success;
    }
    /**
     * @return {Array.<module:model/Error>}
     */
    getWarnings() {
        return this.warnings;
    }

    /**
     * @param {Array.<module:model/Error>} warnings
     */
    setWarnings(warnings) {
        this['warnings'] = warnings;
    }

}



/**
 * @member {Array.<module:model/WithFieldCodeError>} errors
 */
Response.prototype['errors'] = undefined;

/**
 * @member {Array.<Object>} success
 */
Response.prototype['success'] = undefined;

/**
 * @member {Array.<module:model/Error>} warnings
 */
Response.prototype['warnings'] = undefined;






export default Response;