/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TimelineTransaction from './TimelineTransaction';

/**
 * The TimelineTransactionResponse model module.
 * @module model/TimelineTransactionResponse
 * @version 1.2.1
 */
class TimelineTransactionResponse {
    /**
     * Constructs a new <code>TimelineTransactionResponse</code>.
     * @alias module:model/TimelineTransactionResponse
     * @param transaction {module:model/TimelineTransaction} 
     */
    constructor(transaction) {

        TimelineTransactionResponse.initialize(this, transaction);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, transaction) {
        obj['transaction'] = transaction;
    }

    /**
     * Constructs a <code>TimelineTransactionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TimelineTransactionResponse} obj Optional instance to populate.
     * @return {module:model/TimelineTransactionResponse} The populated <code>TimelineTransactionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TimelineTransactionResponse();

            if (data.hasOwnProperty('transaction')) {
                obj['transaction'] = TimelineTransaction.constructFromObject(data['transaction']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TimelineTransactionResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TimelineTransactionResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TimelineTransactionResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `transaction`
        if (data['transaction']) { // data not null
            TimelineTransaction.validateJSON(data['transaction']);
        }

        return true;
    }

    /**
     * @return {module:model/TimelineTransaction}
     */
    getTransaction() {
        return this.transaction;
    }

    /**
     * @param {module:model/TimelineTransaction} transaction
     */
    setTransaction(transaction) {
        this['transaction'] = transaction;
    }

}

TimelineTransactionResponse.RequiredProperties = ["transaction"];

/**
 * @member {module:model/TimelineTransaction} transaction
 */
TimelineTransactionResponse.prototype['transaction'] = undefined;






export default TimelineTransactionResponse;