/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
 * Enum class WalletType.
 * @enum {}
 * @readonly
 */
export default class WalletType {

    /**
     * value: "debit"
     * @const
     */
    "debit" = "debit";


    /**
     * value: "credit"
     * @const
     */
    "credit" = "credit";



    /**
     * Returns a <code>WalletType</code> enum value from a Javascript object name.
     * @param {Object} data The plain JavaScript object containing the name of the enum value.
     * @return {module:model/WalletType} The enum <code>WalletType</code> value.
     */
    static constructFromObject(object) {
        return object;
    }
}