/**
 * BCorrespondent. Tag (v1.1.0). Commit (dbcf8d6)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AmountInDayOfWeek from './AmountInDayOfWeek';
import GapItemTime from './GapItemTime';

/**
 * The WeekHourlyTransaction model module.
 * @module model/WeekHourlyTransaction
 * @version 1.1.0
 */
class WeekHourlyTransaction {
    /**
     * Constructs a new <code>WeekHourlyTransaction</code>.
     * @alias module:model/WeekHourlyTransaction
     * @param amountInDayOfWeek {Array.<module:model/AmountInDayOfWeek>} 
     * @param from {module:model/GapItemTime} 
     * @param to {module:model/GapItemTime} 
     * @param total {Number} 
     */
    constructor(amountInDayOfWeek, from, to, total) {

        WeekHourlyTransaction.initialize(this, amountInDayOfWeek, from, to, total);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amountInDayOfWeek, from, to, total) {
        obj['amountInDayOfWeek'] = amountInDayOfWeek;
        obj['from'] = from;
        obj['to'] = to;
        obj['total'] = total;
    }

    /**
     * Constructs a <code>WeekHourlyTransaction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WeekHourlyTransaction} obj Optional instance to populate.
     * @return {module:model/WeekHourlyTransaction} The populated <code>WeekHourlyTransaction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WeekHourlyTransaction();

            if (data.hasOwnProperty('amountInDayOfWeek')) {
                obj['amountInDayOfWeek'] = ApiClient.convertToType(data['amountInDayOfWeek'], [AmountInDayOfWeek]);
            }
            if (data.hasOwnProperty('from')) {
                obj['from'] = GapItemTime.constructFromObject(data['from']);
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = GapItemTime.constructFromObject(data['to']);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WeekHourlyTransaction</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WeekHourlyTransaction</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WeekHourlyTransaction.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['amountInDayOfWeek']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['amountInDayOfWeek'])) {
                throw new Error("Expected the field `amountInDayOfWeek` to be an array in the JSON data but got " + data['amountInDayOfWeek']);
            }
            // validate the optional field `amountInDayOfWeek` (array)
            for (const item of data['amountInDayOfWeek']) {
                AmountInDayOfWeek.validateJSON(item);
            };
        }
        // validate the optional field `from`
        if (data['from']) { // data not null
            GapItemTime.validateJSON(data['from']);
        }
        // validate the optional field `to`
        if (data['to']) { // data not null
            GapItemTime.validateJSON(data['to']);
        }

        return true;
    }

    /**
     * @return {Array.<module:model/AmountInDayOfWeek>}
     */
    getAmountInDayOfWeek() {
        return this.amountInDayOfWeek;
    }

    /**
     * @param {Array.<module:model/AmountInDayOfWeek>} amountInDayOfWeek
     */
    setAmountInDayOfWeek(amountInDayOfWeek) {
        this['amountInDayOfWeek'] = amountInDayOfWeek;
    }
    /**
     * @return {module:model/GapItemTime}
     */
    getFrom() {
        return this.from;
    }

    /**
     * @param {module:model/GapItemTime} from
     */
    setFrom(from) {
        this['from'] = from;
    }
    /**
     * @return {module:model/GapItemTime}
     */
    getTo() {
        return this.to;
    }

    /**
     * @param {module:model/GapItemTime} to
     */
    setTo(to) {
        this['to'] = to;
    }
    /**
     * @return {Number}
     */
    getTotal() {
        return this.total;
    }

    /**
     * @param {Number} total
     */
    setTotal(total) {
        this['total'] = total;
    }

}

WeekHourlyTransaction.RequiredProperties = ["amountInDayOfWeek", "from", "to", "total"];

/**
 * @member {Array.<module:model/AmountInDayOfWeek>} amountInDayOfWeek
 */
WeekHourlyTransaction.prototype['amountInDayOfWeek'] = undefined;

/**
 * @member {module:model/GapItemTime} from
 */
WeekHourlyTransaction.prototype['from'] = undefined;

/**
 * @member {module:model/GapItemTime} to
 */
WeekHourlyTransaction.prototype['to'] = undefined;

/**
 * @member {Number} total
 */
WeekHourlyTransaction.prototype['total'] = undefined;






export default WeekHourlyTransaction;