/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Currency from './Currency';
import WithdrawalStatus from './WithdrawalStatus';

/**
 * The WithdrawalHistoryItem model module.
 * @module model/WithdrawalHistoryItem
 * @version 1.2.1
 */
class WithdrawalHistoryItem {
    /**
     * Constructs a new <code>WithdrawalHistoryItem</code>.
     * @alias module:model/WithdrawalHistoryItem
     * @param amount {Number} 
     * @param created {String} 
     * @param currency {module:model/Currency} 
     * @param ident {Number} 
     * @param initiator {String} 
     * @param withdrawalStatus {module:model/WithdrawalStatus} 
     */
    constructor(amount, created, currency, ident, initiator, withdrawalStatus) {

        WithdrawalHistoryItem.initialize(this, amount, created, currency, ident, initiator, withdrawalStatus);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, created, currency, ident, initiator, withdrawalStatus) {
        obj['amount'] = amount;
        obj['created'] = created;
        obj['currency'] = currency;
        obj['ident'] = ident;
        obj['initiator'] = initiator;
        obj['withdrawalStatus'] = withdrawalStatus;
    }

    /**
     * Constructs a <code>WithdrawalHistoryItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WithdrawalHistoryItem} obj Optional instance to populate.
     * @return {module:model/WithdrawalHistoryItem} The populated <code>WithdrawalHistoryItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WithdrawalHistoryItem();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = Currency.constructFromObject(data['currency']);
            }
            if (data.hasOwnProperty('ident')) {
                obj['ident'] = ApiClient.convertToType(data['ident'], 'Number');
            }
            if (data.hasOwnProperty('initiator')) {
                obj['initiator'] = ApiClient.convertToType(data['initiator'], 'String');
            }
            if (data.hasOwnProperty('withdrawalStatus')) {
                obj['withdrawalStatus'] = WithdrawalStatus.constructFromObject(data['withdrawalStatus']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WithdrawalHistoryItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WithdrawalHistoryItem</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WithdrawalHistoryItem.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['created'] && !(typeof data['created'] === 'string' || data['created'] instanceof String)) {
            throw new Error("Expected the field `created` to be a primitive type in the JSON string but got " + data['created']);
        }
        // ensure the json data is a string
        if (data['initiator'] && !(typeof data['initiator'] === 'string' || data['initiator'] instanceof String)) {
            throw new Error("Expected the field `initiator` to be a primitive type in the JSON string but got " + data['initiator']);
        }

        return true;
    }

    /**
     * @return {Number}
     */
    getAmount() {
        return this.amount;
    }

    /**
     * @param {Number} amount
     */
    setAmount(amount) {
        this['amount'] = amount;
    }
    /**
     * @return {String}
     */
    getCreated() {
        return this.created;
    }

    /**
     * @param {String} created
     */
    setCreated(created) {
        this['created'] = created;
    }
    /**
     * @return {module:model/Currency}
     */
    getCurrency() {
        return this.currency;
    }

    /**
     * @param {module:model/Currency} currency
     */
    setCurrency(currency) {
        this['currency'] = currency;
    }
    /**
     * minimum: -9223372036854775808
     * maximum: 9223372036854775807
     * @return {Number}
     */
    getIdent() {
        return this.ident;
    }

    /**
     * @param {Number} ident
     */
    setIdent(ident) {
        this['ident'] = ident;
    }
    /**
     * @return {String}
     */
    getInitiator() {
        return this.initiator;
    }

    /**
     * @param {String} initiator
     */
    setInitiator(initiator) {
        this['initiator'] = initiator;
    }
    /**
     * @return {module:model/WithdrawalStatus}
     */
    getWithdrawalStatus() {
        return this.withdrawalStatus;
    }

    /**
     * @param {module:model/WithdrawalStatus} withdrawalStatus
     */
    setWithdrawalStatus(withdrawalStatus) {
        this['withdrawalStatus'] = withdrawalStatus;
    }

}

WithdrawalHistoryItem.RequiredProperties = ["amount", "created", "currency", "ident", "initiator", "withdrawalStatus"];

/**
 * @member {Number} amount
 */
WithdrawalHistoryItem.prototype['amount'] = undefined;

/**
 * @member {String} created
 */
WithdrawalHistoryItem.prototype['created'] = undefined;

/**
 * @member {module:model/Currency} currency
 */
WithdrawalHistoryItem.prototype['currency'] = undefined;

/**
 * @member {Number} ident
 */
WithdrawalHistoryItem.prototype['ident'] = undefined;

/**
 * @member {String} initiator
 */
WithdrawalHistoryItem.prototype['initiator'] = undefined;

/**
 * @member {module:model/WithdrawalStatus} withdrawalStatus
 */
WithdrawalHistoryItem.prototype['withdrawalStatus'] = undefined;






export default WithdrawalHistoryItem;