/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
 * Enum class WithdrawalStatus.
 * @enum {}
 * @readonly
 */
export default class WithdrawalStatus {

    /**
     * value: "registered"
     * @const
     */
    "registered" = "registered";


    /**
     * value: "processing"
     * @const
     */
    "processing" = "processing";


    /**
     * value: "confirmed"
     * @const
     */
    "confirmed" = "confirmed";


    /**
     * value: "declined"
     * @const
     */
    "declined" = "declined";



    /**
     * Returns a <code>WithdrawalStatus</code> enum value from a Javascript object name.
     * @param {Object} data The plain JavaScript object containing the name of the enum value.
     * @return {module:model/WithdrawalStatus} The enum <code>WithdrawalStatus</code> value.
     */
    static constructFromObject(object) {
        return object;
    }
}