/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WithFieldCodeError model module.
 * @module model/WithFieldCodeError
 * @version 1.2.1
 */
class WithFieldCodeError {
    /**
     * Constructs a new <code>WithFieldCodeError</code>.
     * @alias module:model/WithFieldCodeError
     * @param code {Number} 
     * @param message {String} 
     */
    constructor(code, message) {

        WithFieldCodeError.initialize(this, code, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, message) {
        obj['code'] = code;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>WithFieldCodeError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WithFieldCodeError} obj Optional instance to populate.
     * @return {module:model/WithFieldCodeError} The populated <code>WithFieldCodeError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WithFieldCodeError();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = ApiClient.convertToType(data['meta'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WithFieldCodeError</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WithFieldCodeError</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WithFieldCodeError.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }

    /**
     * minimum: -9223372036854775808
     * maximum: 9223372036854775807
     * @return {Number}
     */
    getCode() {
        return this.code;
    }

    /**
     * @param {Number} code
     */
    setCode(code) {
        this['code'] = code;
    }
    /**
     * @return {String}
     */
    getMessage() {
        return this.message;
    }

    /**
     * @param {String} message
     */
    setMessage(message) {
        this['message'] = message;
    }
    /**
     * Returns Arbitrary JSON object.
     * @return {Object}
     */
    getMeta() {
        return this.meta;
    }

    /**
     * Sets Arbitrary JSON object.
     * @param {Object} meta Arbitrary JSON object.
     */
    setMeta(meta) {
        this['meta'] = meta;
    }

}

WithFieldCodeError.RequiredProperties = ["code", "message"];

/**
 * @member {Number} code
 */
WithFieldCodeError.prototype['code'] = undefined;

/**
 * @member {String} message
 */
WithFieldCodeError.prototype['message'] = undefined;

/**
 * Arbitrary JSON object.
 * @member {Object} meta
 */
WithFieldCodeError.prototype['meta'] = undefined;






export default WithFieldCodeError;