/**
 * BCorrespondent. Tag (-). Commit (bb65df7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WithdrawalHistoryItem from './WithdrawalHistoryItem';

/**
 * The WithdrawalHistory model module.
 * @module model/WithdrawalHistory
 * @version 1.2.1
 */
class WithdrawalHistory {
    /**
     * Constructs a new <code>WithdrawalHistory</code>.
     * @alias module:model/WithdrawalHistory
     * @param items {Array.<module:model/WithdrawalHistoryItem>} 
     * @param total {Number} 
     */
    constructor(items, total) {

        WithdrawalHistory.initialize(this, items, total);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, items, total) {
        obj['items'] = items;
        obj['total'] = total;
    }

    /**
     * Constructs a <code>WithdrawalHistory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WithdrawalHistory} obj Optional instance to populate.
     * @return {module:model/WithdrawalHistory} The populated <code>WithdrawalHistory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WithdrawalHistory();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [WithdrawalHistoryItem]);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WithdrawalHistory</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WithdrawalHistory</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WithdrawalHistory.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                WithdrawalHistoryItem.validateJSON(item);
            };
        }

        return true;
    }

    /**
     * @return {Array.<module:model/WithdrawalHistoryItem>}
     */
    getItems() {
        return this.items;
    }

    /**
     * @param {Array.<module:model/WithdrawalHistoryItem>} items
     */
    setItems(items) {
        this['items'] = items;
    }
    /**
     * minimum: -9223372036854775808
     * maximum: 9223372036854775807
     * @return {Number}
     */
    getTotal() {
        return this.total;
    }

    /**
     * @param {Number} total
     */
    setTotal(total) {
        this['total'] = total;
    }

}

WithdrawalHistory.RequiredProperties = ["items", "total"];

/**
 * @member {Array.<module:model/WithdrawalHistoryItem>} items
 */
WithdrawalHistory.prototype['items'] = undefined;

/**
 * @member {Number} total
 */
WithdrawalHistory.prototype['total'] = undefined;






export default WithdrawalHistory;