/**
 * BCorrespondent. Tag (v1.0.0). Commit (9e7bfa7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', process.cwd() + '/src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require(process.cwd() + '/src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.BCorrespondentTagV100Commit9e7bfa7);
    }
}(this, function(expect, BCorrespondentTagV100Commit9e7bfa7) {
    'use strict';

    var instance;

    beforeEach(function() {
        instance = new BCorrespondentTagV100Commit9e7bfa7.Init();
    });

    var getProperty = function(object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function')
            return object[getter]();
        else
            return object[property];
    }

    var setProperty = function(object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function')
            object[setter](value);
        else
            object[property] = value;
    }

    describe('Init', function() {
        it('should create an instance of Init', function() {
            // uncomment below and update the code to test Init
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.Init();
            //expect(instance).to.be.a(BCorrespondentTagV100Commit9e7bfa7.Init);
        });

        it('should have the property isjwtvalid (base name: "isjwtvalid")', function() {
            // uncomment below and update the code to test the property isjwtvalid
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.Init();
            //expect(instance).to.be();
        });

        it('should have the property level (base name: "level")', function() {
            // uncomment below and update the code to test the property level
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.Init();
            //expect(instance).to.be();
        });

        it('should have the property loadcsslocally (base name: "loadcsslocally")', function() {
            // uncomment below and update the code to test the property loadcsslocally
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.Init();
            //expect(instance).to.be();
        });

        it('should have the property shaxs (base name: "shaxs")', function() {
            // uncomment below and update the code to test the property shaxs
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.Init();
            //expect(instance).to.be();
        });

        it('should have the property telegrambot (base name: "telegrambot")', function() {
            // uncomment below and update the code to test the property telegrambot
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.Init();
            //expect(instance).to.be();
        });

        it('should have the property telegramchat (base name: "telegramchat")', function() {
            // uncomment below and update the code to test the property telegramchat
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.Init();
            //expect(instance).to.be();
        });

        it('should have the property totelegram (base name: "totelegram")', function() {
            // uncomment below and update the code to test the property totelegram
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.Init();
            //expect(instance).to.be();
        });

    });

}));