/**
 * BCorrespondent. Tag (v1.0.0). Commit (9e7bfa7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', process.cwd() + '/src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require(process.cwd() + '/src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.BCorrespondentTagV100Commit9e7bfa7);
    }
}(this, function(expect, BCorrespondentTagV100Commit9e7bfa7) {
    'use strict';

    var instance;

    beforeEach(function() {
        instance = new BCorrespondentTagV100Commit9e7bfa7.TimelineTransaction();
    });

    var getProperty = function(object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function')
            return object[getter]();
        else
            return object[property];
    }

    var setProperty = function(object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function')
            object[setter](value);
        else
            object[property] = value;
    }

    describe('TimelineTransaction', function() {
        it('should create an instance of TimelineTransaction', function() {
            // uncomment below and update the code to test TimelineTransaction
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.TimelineTransaction();
            //expect(instance).to.be.a(BCorrespondentTagV100Commit9e7bfa7.TimelineTransaction);
        });

        it('should have the property amount (base name: "amount")', function() {
            // uncomment below and update the code to test the property amount
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.TimelineTransaction();
            //expect(instance).to.be();
        });

        it('should have the property correspondentBank (base name: "correspondentBank")', function() {
            // uncomment below and update the code to test the property correspondentBank
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.TimelineTransaction();
            //expect(instance).to.be();
        });

        it('should have the property correspondentBankSwiftSepaCode (base name: "correspondentBankSwiftSepaCode")', function() {
            // uncomment below and update the code to test the property correspondentBankSwiftSepaCode
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.TimelineTransaction();
            //expect(instance).to.be();
        });

        it('should have the property currency (base name: "currency")', function() {
            // uncomment below and update the code to test the property currency
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.TimelineTransaction();
            //expect(instance).to.be();
        });

        it('should have the property ident (base name: "ident")', function() {
            // uncomment below and update the code to test the property ident
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.TimelineTransaction();
            //expect(instance).to.be();
        });

        it('should have the property senderAddress (base name: "senderAddress")', function() {
            // uncomment below and update the code to test the property senderAddress
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.TimelineTransaction();
            //expect(instance).to.be();
        });

        it('should have the property senderBank (base name: "senderBank")', function() {
            // uncomment below and update the code to test the property senderBank
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.TimelineTransaction();
            //expect(instance).to.be();
        });

        it('should have the property senderBankAccount (base name: "senderBankAccount")', function() {
            // uncomment below and update the code to test the property senderBankAccount
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.TimelineTransaction();
            //expect(instance).to.be();
        });

        it('should have the property senderName (base name: "senderName")', function() {
            // uncomment below and update the code to test the property senderName
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.TimelineTransaction();
            //expect(instance).to.be();
        });

        it('should have the property senderPhoneNumber (base name: "senderPhoneNumber")', function() {
            // uncomment below and update the code to test the property senderPhoneNumber
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.TimelineTransaction();
            //expect(instance).to.be();
        });

        it('should have the property swiftSepaCode (base name: "swiftSepaCode")', function() {
            // uncomment below and update the code to test the property swiftSepaCode
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.TimelineTransaction();
            //expect(instance).to.be();
        });

    });

}));