/**
 * BCorrespondent. Tag (v1.0.0). Commit (9e7bfa7)
 * BCorrespondent server api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: fclaw007@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD.
        define(['expect.js', process.cwd() + '/src/index'], factory);
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        factory(require('expect.js'), require(process.cwd() + '/src/index'));
    } else {
        // Browser globals (root is window)
        factory(root.expect, root.BCorrespondentTagV100Commit9e7bfa7);
    }
}(this, function(expect, BCorrespondentTagV100Commit9e7bfa7) {
    'use strict';

    var instance;

    beforeEach(function() {
        instance = new BCorrespondentTagV100Commit9e7bfa7.WithFieldCodeError();
    });

    var getProperty = function(object, getter, property) {
        // Use getter method if present; otherwise, get the property directly.
        if (typeof object[getter] === 'function')
            return object[getter]();
        else
            return object[property];
    }

    var setProperty = function(object, setter, property, value) {
        // Use setter method if present; otherwise, set the property directly.
        if (typeof object[setter] === 'function')
            object[setter](value);
        else
            object[property] = value;
    }

    describe('WithFieldCodeError', function() {
        it('should create an instance of WithFieldCodeError', function() {
            // uncomment below and update the code to test WithFieldCodeError
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.WithFieldCodeError();
            //expect(instance).to.be.a(BCorrespondentTagV100Commit9e7bfa7.WithFieldCodeError);
        });

        it('should have the property code (base name: "code")', function() {
            // uncomment below and update the code to test the property code
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.WithFieldCodeError();
            //expect(instance).to.be();
        });

        it('should have the property message (base name: "message")', function() {
            // uncomment below and update the code to test the property message
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.WithFieldCodeError();
            //expect(instance).to.be();
        });

        it('should have the property meta (base name: "meta")', function() {
            // uncomment below and update the code to test the property meta
            //var instance = new BCorrespondentTagV100Commit9e7bfa7.WithFieldCodeError();
            //expect(instance).to.be();
        });

    });

}));